### PR TITLE
Introduce placement strategy + add natural order placement

### PR DESCRIPTION
**Pull request by jDramaix**

### CODE REVIEW

**Comment by christiangoudreau** [comment]
Looks good, but why doesn't it compile?

@meriouma could you take a look please?

**Comment by jDramaix** [comment]
I forgot to update the version of the gwt maven plugin

**Comment by christiangoudreau** [comment]
LGTM

**Comment by jDramaix** [comment]
@spg Can you try to use the `PlacementStrategy.NATURAL_ORDER` in lille ?

**Comment by spg** [comment]
Yep, will do

On Tue, Jan 27, 2015 at 5:12 AM, Julien Dramaix <notifications@github.com>
wrote:

> @spg <https://github.com/spg> Can you try to use the
> PlacementStrategy.NATURAL_ORDER in lille ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArcBees/gwtquery-elastic-plugin/pull/15#issuecomment-71621190>
> .
>



-- 
*Simon-Pierre Gingras | *Developer
M: 418.929.0230 *|* T: @spgingras *| *G+: SP Gingras
ArcBees <http://www.arcbees.com/> *|* Blog <http://blog.arcbees.com/> *|*
Facebook <http://facebook.com/QueenOfTheBees> *|* LinkedIn
<http://www.linkedin.com/company/arcbees>

**Pull request merged**
